-- =========================================================
-- SOLO para una base que YA está corriendo y tiene los IDs de zona con huecos (ej. 1, 4, 5, 6, 7 — quedaron
-- así porque una carga fallida vieja gastó números de la secuencia): los renumera de corrido, 1, 2, 3, 4, 5,
-- en el orden de dificultad (min_level). Una instalación nueva ya sale consecutiva (no hace falta correrlo).
--
-- Por qué importa: /zona, /zonas, /profile y /forge recipes muestran el ID ("Zona 4"), y con huecos la segunda
-- zona se llamaba "Zona 4".
--
-- Actualiza TODO lo que guarda un ID de zona, de forma consistente y en UNA transacción (si algo falla no queda
-- nada a medias): zones.zone_id, monsters.zone_id, recipes.zone_id, users.current_zone_id y
-- users.highest_zone_cleared (0 = ninguna, se deja). Las claves foráneas a zones se sueltan un momento (Postgres
-- no las deja cambiar de valor mientras están) y se vuelven a crear IGUALES; la secuencia queda apuntando al
-- próximo número libre para que una zona nueva sea la 6.
--
-- Re-ejecutable: si los IDs ya son 1..N en orden, no hace nada. Correrlo con el BOT APAGADO.
-- =========================================================

BEGIN;

CREATE TEMP TABLE zone_id_map ON COMMIT DROP AS
SELECT zone_id AS old_id, ROW_NUMBER() OVER (ORDER BY min_level, zone_id)::INTEGER AS new_id
FROM zones;

DO $$
DECLARE
    fk RECORD;
    next_id INTEGER;
BEGIN
    -- Nada que hacer si ya están consecutivas.
    IF NOT EXISTS (SELECT 1 FROM zone_id_map WHERE old_id <> new_id) THEN
        RAISE NOTICE 'renumber_zones_consecutively: los IDs de zona ya son consecutivos, no se toca nada.';
        RETURN;
    END IF;

    -- 1) Soltar las FK que apuntan a zones (guardando su definición exacta para recrearlas idénticas).
    CREATE TEMP TABLE zone_fks ON COMMIT DROP AS
    SELECT conrelid::regclass::TEXT AS table_name, conname, pg_get_constraintdef(oid) AS definition
    FROM pg_constraint
    WHERE confrelid = 'zones'::regclass AND contype = 'f';

    FOR fk IN SELECT * FROM zone_fks LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', fk.table_name, fk.conname);
    END LOOP;

    -- 2) Renumerar. En zones se hace en dos pasos (primero fuera de rango, después al valor final) porque
    --    la clave primaria no deja pasar por un ID ocupado (ej. 6 -> 4 mientras el 4 todavía existe).
    --    zone_id es GENERATED ALWAYS: hay que pasarla a BY DEFAULT para poder actualizarla.
    ALTER TABLE zones ALTER COLUMN zone_id SET GENERATED BY DEFAULT;
    UPDATE zones SET zone_id = zone_id + 1000000;
    UPDATE zones z SET zone_id = m.new_id FROM zone_id_map m WHERE z.zone_id = m.old_id + 1000000;
    ALTER TABLE zones ALTER COLUMN zone_id SET GENERATED ALWAYS;

    -- Las tablas que la referencian no tienen restricción de unicidad sobre el ID: un solo UPDATE alcanza.
    UPDATE monsters t SET zone_id = m.new_id FROM zone_id_map m WHERE t.zone_id = m.old_id;
    UPDATE recipes  t SET zone_id = m.new_id FROM zone_id_map m WHERE t.zone_id = m.old_id;
    UPDATE users    t SET current_zone_id = m.new_id FROM zone_id_map m WHERE t.current_zone_id = m.old_id;
    UPDATE users    t SET highest_zone_cleared = m.new_id FROM zone_id_map m WHERE t.highest_zone_cleared = m.old_id;
    -- v0.10.0: pet_species.zone_id (una especie por zona: UNIQUE, así que se pasa primero por +1000000 para que no choquen dos a mitad del UPDATE). Solo si la tabla existe.
    IF to_regclass('pet_species') IS NOT NULL THEN
        UPDATE pet_species SET zone_id = zone_id + 1000000;
        UPDATE pet_species t SET zone_id = m.new_id FROM zone_id_map m WHERE t.zone_id = m.old_id + 1000000;
    END IF;

    -- 3) Recrear las FK, idénticas a como estaban.
    FOR fk IN SELECT * FROM zone_fks LOOP
        EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', fk.table_name, fk.conname, fk.definition);
    END LOOP;

    -- 4) La secuencia sigue en el número viejo (ej. 8): que la próxima zona sea la N+1.
    SELECT COALESCE(MAX(zone_id), 0) + 1 INTO next_id FROM zones;
    EXECUTE format('ALTER TABLE zones ALTER COLUMN zone_id RESTART WITH %s', next_id);
END $$;

COMMIT;

-- Chequeo: IDs 1..N en orden de nivel, y ningún ID huérfano.
-- SELECT zone_id, name, min_level FROM zones ORDER BY min_level;
-- SELECT count(*) FROM monsters WHERE zone_id NOT IN (SELECT zone_id FROM zones);   -- 0
-- SELECT count(*) FROM users WHERE current_zone_id NOT IN (SELECT zone_id FROM zones);   -- 0
